# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_qsi_pulse_reader_wrappers", use_symbols = TRUE, package_name = "qsi.pulse.reader")

#' @usage NULL
#' @useDynLib qsi.pulse.reader, .registration = TRUE
NULL

#' Environment holding methods for the PulseReader reference-like object.
#'
#' Users construct via `PulseReader$new("pulses.bin")`.
#' @export
PulseReader <- new.env(parent = emptyenv())

PulseReader$new <- function(file_name) .Call(wrap__PulseReader__new, file_name)

PulseReader$get_all_records <- function(aperture_index) .Call(wrap__PulseReader__get_all_records, self, aperture_index)

PulseReader$get_pulses <- function(aperture_index) .Call(wrap__PulseReader__get_pulses, self, aperture_index)

#' @export
`$.PulseReader` <- function (self, name) { func <- PulseReader[[name]]; environment(func) <- environment(); func }

#' @export
`[[.PulseReader` <- `$.PulseReader`


# nolint end
