name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.17"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "python/pyproject.toml"

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: "stable"

    - name: Run Rust tests
      working-directory: ./rust-core
      run: cargo test

    - name: Build and install Python interface
      run: uv pip install --system ./python[test]

    - name: Run Python tests
      run: uv run pytest ./python
